### ISSUE TITLE
webgui/SamplerBox.API missing

### ISSUE THREAD

**Issue by alexmacrae** [hansehv/SamplerBox#18]
Seems as though this file is required by the webgui to work.

**Comment by hansehv** [comment]
The webgui html files need to accessed via the GUI, not directly from disk as all needed variables from the active SB script will not be initialized via the API url.
This variable are in a "file" generated by the http-thread in the box as the API for communicating between samplerbox and web traffic. In that respect it is the most crucial "file" indeed.
Please open the readme.html and http_gui.py for further explanation of the interface. Ofcourse also all examples in the readme.html will not show up when you're not accessing the pages from http connection with samplerbox.
Please feedback if this answers your question, so the issue can be closed.

**Comment by alexmacrae** [comment]
Seems I jumped the gun by exploring the html before running SB! My bad! Thanks for explaining that.
