### ISSUE TITLE
Midi CC can turn filter on but not off

### ISSUE THREAD

**Issue by kaixxx** [hansehv/SamplerBox#41]
I am testing the branch "Limiter-and-Overdrive" (because it is great that you can now have a filter on from the start!)

My problem: I have assigend a button on my keyboard to a filter toggle in CCmap.csv:
Part1Btn,Fixed,Reverb,Toggle
If I press the button, the filter is turned on correctly. But if I press it again, the filter does not turn off. Very strange is, that the HTML-Gui showes the filter as off but I can still hear it. I have checked this with some very extrem settings where you can clearly distinguish by ear if the filter is on or off. 
The same problem repeats with all the other buttons that I have assigend to filters.

**Comment by hansehv** [comment]
Hello kaixx,
I did not notice this before, but can reproduce it. Working on it, thanks for the issue.

**Comment by hansehv** [comment]
Hello kaixxx,
Appeared easy to fix, it should work after replacing Cpp.py.
Please confirm, thanks in advance, Hans

**Comment by kaixxx** [comment]
Tested your fix, works great. Thank you!
(You can close this issue now.)

**Comment by hansehv** [comment]
Thanks for report and feedback
