### ISSUE TITLE
ImportError: No module named Cython.Build

### ISSUE THREAD

**Issue by ghost** [hansehv/SamplerBox#76]
I try to Install it on the Raspberry Pi Image "2021-10-30-raspios-bullseye-armhf-lite"

After this: sudo python setup.py build_ext --inplace
Result:
File "setup.py", line 2, in <module>
    from Cython.Build import cythonize
ImportError: No module named Cython.Build

Has Anyone the Same Problems to Install it or is there a guide for that?

**Comment by hansehv** [comment]
Your system misses a prereq, maybe it can be solved with 'sudo pip install cython'.
However you might encounter a lot more missing prereqs.
Considering you use a lite version, you might may want to make a samplerbox-only PI. In that case you can also use the image supplied on homspace.nl/samplerbox.

**Comment by ghost** [comment]
My result is:
`pi@raspberrypi:~ $ sudo pip install cython
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: cython in /usr/lib/python3/dist-packages (0.29.21)`

`pi@raspberrypi:~/SamplerBox $ sudo python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from Cython.Build import cythonize
ImportError: No module named Cython.Build`

I need a Chromium in Kiosk-Mode in my Samplerbox. I Tried to Install it on the Image but with no success.

I Installed Python3 and a other things:
`sudo apt-get update ; sudo apt-get -y install git python3-dev python3-pip python3-numpy cython python3-smbus portaudio19-dev libportaudio2 libffi-dev
sudo pip install rtmidi-python pyaudio cffi sounddevice`

do I Need Python and not Python3 Stuff?

**Comment by hansehv** [comment]
The current image is very hard for installing extra stuff and very outdated. Planned to be replaced together with next change:
You can see the master is python2.7 by just looking at the source. Within a few weeks the python3 version will be published (and here python3 branch will merge with master).

**Comment by hansehv** [comment]
Published new version here on 06-02, documentation site updated same date.
