### ISSUE TITLE
Error building the project

### ISSUE THREAD

**Issue by frederico-betting** [hansehv/SamplerBox#81]
Hi,

I'm trying to build the project locally but I'm facing some issues with the `midi` library.

In the file `smfplayer.py` there are 2 imports:

```python
import midi
import midi.sequencer as sequencer
```

The first one is ok. I've built `python-midi` library available in https://github.com/hansehv/python-midi / branch: `python3` and installed manually. Python found the lib.

The problem is the second one. What should I do to have the other import available? Thanks

**Comment by hansehv** [comment]
Hi Frederico,
..I forgot to python3 into master, another todo.. thanks for pointinh that out.
But you found the correct one, so it should be OK as sequencer is a class in the lib and goal of the second statement is using "midi.sequencer" in every reference.
The only thing I can think of now is that samplerbox needs to run as root, so the setup should also be executed as "sudo python setup.py install".
There is a small chance there is another midi lib on your system.

**Comment by frederico-betting** [comment]
Nice... I'll try with sudo. Thanks

Just a side note here...
My plan would be to try to install SamplerBox in different boards (not in raspberry pi only). Then I have some questions:

1. Do you have any plan to support different boards?
2. I took a look at the code and it would be necessary a lot of refactoring. In case I work on it, would you support adding code changes/refactoring in this repo or do you think it worth to work on a forked repo?

**Comment by hansehv** [comment]
Meanwhile executed the delayed merge (sorry for the inconvenience)

It's not my goal to support different boards, but extra's not harming my own purpose (=being a useful and easy to enhance device in my band) are usually welcome.

But I don't get the full scope your question.

At this moment the software is running on more hardware than raspberry pi. For debian linux systems it's usually out of the box.
As long as the board can run a general linux dist having the right python and C++ libs, it should not need a lot of refactoring. And I think/hope such differences can be nicely split off into platform dependent modules, the same way peripherals (like displays) are dealt with. This would be a welcome contribution.

But if you mean by refactoring "porting to another software platform", then I would like to get an idea of the impact before I'm able to give you a proper answer.

By the way: via GitHub I only support contributions from forks, so the question is whether I would accept & merge them.

**Comment by frederico-betting** [comment]
I was not thinking about porting to any other technology. Python is fine. 
I was thinking about separating in modules/packages and responsibilities to make it easier to maintain and expand. 

So... I'll start working on it and let you know what I'm planning to do. I'd love to contribute in this project... this is amazing.

I first need to understand how it works and make it work from scratch locally. I'm already working on it.
