### ISSUE TITLE
Rotate SPI Oled display 180°

### ISSUE THREAD

**Issue by KeenVox** [hansehv/SamplerBox#87]
Hi, 
I'm using a 0,96 OLED for my samplerbox over SPI. I'm designing a little hat for the pi and for that I need to rotate the display 180 degrees. Is there away to configure this anywhere?

Thx in advance!
Greets
Keen

**Comment by hansehv** [comment]
Hi Keen,
It's not available as a configuration parameter (yet).
As I don't have such hardware myself, I can't experiment/test.
You might try to change the applicable rotate parameter in OLED.py from 2 to 0 (they are at lines 63 and 65)
If this works, I will add this as a configuration parameter.
Regards, Hans

**Comment by KeenVox** [comment]
Hey Hans,
thx for your help. Tried it and it works like a charm :-)

Greets
Keen

**Comment by hansehv** [comment]
Hi Keen,
Thanks for the feedback. Next release will have this in the configuration.txt.
Regards, Hans
